# Generated by Django 5.0.6 on 2024-05-12 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("earthquake_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Search result",
                "verbose_name_plural": "Search results",
            },
        ),
    ]
