# Generated by Django 5.0.6 on 2024-05-16 12:24

from django.db import migrations

from core.models import City

cities = (
    {
        "name": "Los Angeles",
        "state": "CA",
        "country": "USA",
        "lat": 34.0522,
        "long": -118.2437,
    }, {
        "name": "Tokyo",
        "state": "Tokyo",
        "country": "Japan",
        "lat": 35.652832,
        "long": 139.839478,
    }, {
        "name": "San Francisco",
        "state": "CA",
        "country": "USA",
        "lat": 37.773972,
        "long": -122.431297,
    }

)


class Migration(migrations.Migration):

    def forwards(apps, schema_editor):
        if schema_editor.connection.alias != "default":
            return
        for city in cities:
            City.objects.create(**city)

    dependencies = [
        ('core', '0002_searchresult'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
